[project]
name = "mr-t"
version = "1.0.0"
description = "connect to Eiger, stream to file and UDP"
readme = "README.md"
requires-python = ">=3.13"
license = "GPL-3.0-or-later"
dependencies = [
    "asyncudp==0.11.0",
    "culsans==0.11.0",
    "h5py==3.16.0",
    "pydantic==2.13.4",
    "pyzmq==27.1.0",
    "structlog==26.1.0",
    "typed-argument-parser==1.12.0",
]
authors = [
  {name = "Philipp Middendorf", email = "philipp.middendorf@desy.de"}
]

[project.scripts]
mr_t_server = "mr_t.server:main"
dummy_client = "mr_t.dummy_client:main"

[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"

[tool.ty.rules]
all = "error"

[tool.isort]
profile = "black"
force_single_line = "true"

[dependency-groups]
dev = [
    "ruff>=0.15.20",
    "ty==0.0.57",
]

[tool.ruff]
target-version = "py313"

[tool.ruff.lint.isort]
force-single-line = true

[tool.ruff.lint]
# to turn this:
#
# from X import y,z
#
# into
#
# from X import y
# from X import z
select = ["I001", "F", "E", "W", "I", "N", "UP", "YTT", "ANN", "ASYNC", "S", "FBT", "B", "A", "C4", "T10", "ICN", "LOG", "G", "PIE", "T20", "PYI", "Q", "RET", "SLF", "SLOT", "SIM", "TID", "TC", "INT", "ARG", "PTH", "TD", "FIX", "PD", "PGH", "PL", "R", "W", "FLY", "NPY", "FAST", "AIR", "FURB", "RUF"]
ignore = ["E501", "E722", "UP035", "ANN401", "S101", "S310", "FBT001", "B017", "B008", "B904", "C405", "C401", "C400", "G004", "G003", "PYI041", "SIM105", "TC001", "PGH003", "PGH004", "PLR2004", "PLR0913", "PLR0915", "PLR0912", "PLR0911", "RUF001", "LOG015"]


